# Generated by Django 5.0.6 on 2024-07-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='org_id',
            new_name='orgId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userId',
        ),
    ]
